name: Validation Tests

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r netpen/requirements.txt
        pip install -r dev/requirements.txt
    - name: Lint
      run: make lint
    - name: pycodestyle
      run: make pycodestyle
    - name: Run Tests
      run: PYTHONPATH=. pytest dev/tests/validation-tests --junitxml=junit/validation-test-results.xml
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: junit/validation-test-results.xml
        pull_request_build: commit
